### ISSUE TITLE
Text editor bugs/enhancements

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#107]
When selecting inline instances e.g. bold/italic or link inside a paragraph or other text editable components, currently toolbar doesn't know that user selects an instance and would execute the same command again.

Instead it should be made aware that user has selected part or entire instance and show "active" state in the toolbar, then when clicked again it should turn selected instance text back to text.

This is a follow-up from https://github.com/webstudio-is/webstudio-designer/pull/93

## Todo
- [x] inform toolbar about selected instance
- [x] support selecting part of the word
- [x] when turning instance to text, make sure it works both entire word and part of it
- [x] italicizing text removes bold
- [x] apply the new design from figma (icons, styling)

**Comment by taylornowotny** [comment]
issues:
- still can't click or highlight text that is bold or decorated
- italicizing text removes bold
- if text element is near the top of the canvas, the toolbar may be off screen
- after double-clicking to edit text in a text block, user can no longer de-select the text block. The thick blue border remains forever and single-clicking the text block goes right into edit mode rather than selecting it

- sometimes double-clicking the text element removes all text and shows a large area with a dotted outline. Not exactly sure how to recreate but if you click rapidly around the canvas when a text element is there I'm sure it'll bug out. Happened to me a few times (photo)
<img width="384" alt="Screen Shot 2022-07-05 at 9 48 46 AM" src="https://user-images.githubusercontent.com/86495896/177378089-2a0dd224-4d6a-4906-8810-3ce10ff769ee.png">

**Comment by kof** [comment]
- [ ] deleteing text doesn't hide the toolbar

**Comment by taylornowotny** [comment]
Check the Design System docs in figma for design details!

<img width="238" alt="Screenshot 2022-11-14 at 11 18 12 AM" src="https://user-images.githubusercontent.com/86495896/201749126-81f2b0c7-267f-4531-baea-f1d392b41db6.png">

**Comment by kof** [comment]
Done?
