### ISSUE TITLE
Enable drag&drop in the tree navigator

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#131]
We need to be able to reorder items in the tree navigator because that's often easier than doing it directly on the canvas

## Todo
- [x] enable drag&drop into instances
- [x] ensure user can't drag an instance into an instance that doesn't support instances as children: e.g. paragraph or headline should not support dragging in anything (see canAcceptChild())
- [x] enable dragging horizontally to change the parent but stay at the same level
- [x] disable dragging inline instances out of their parent (e.g. Paragraph can have a Bold), but Bold can't exist top level, only as part of paragraph
- [x] enable scrolling when list is big
- [x] enable hovering over a collapsed tree item, when holding a bit - it opens the item and you can continue dragging inside of it
- [x] animation starts when value changes in style panel (https://share.descript.com/view/qsbbe2UQlVi)

**Comment by kof** [comment]
Definitely check out how Webflow handles this interaction, it works very well!

**Comment by kof** [comment]
cc @kkga @taylornowotny anything else you know we need to be aware regarding drag and drop in tree navigator?

**Comment by kof** [comment]
@taylornowotny do you think we can have some design proposal next week for this? We can start building with "any" design for sure, but I think it would be good to have at least a semi-final version

**Comment by taylornowotny** [comment]
More suggestions:

- [ ] accordion-style opening/closing of parent elements to show/hide the children
- [ ] a collapse-all button
- [ ] ability to pin the navigator panel so it's always open on the left side (I have this permanently enabled in Webflow)

There's also the issue of naming elements.
In Figma you can name layers directly (and most users don't). In Webflow the element name in the navigator is the name of the class.
What do you think our approach should be here?

**Comment by taylornowotny** [comment]
Another thing, how do you want to handle the body HTML tag? Can users change the styles on the tag?

In Webflow the body is always the top level parent. It can be given a class but doesn't need to.

It's useful to be able to select the body element for things like setting the typography defaults for the project, or changing the body to overflow:hidden to prevent page scrolling when a modal is open, for example.

**Comment by kof** [comment]
>  accordion-style opening/closing of parent elements to show/hide the children

Can you clarify more specifically what you think should happen?

**Comment by kof** [comment]
>  ability to pin the navigator panel so it's always open on the left side (I have this permanently enabled in Webflow)

Lets think about this one more carefully. I understand why its useful, but it feels very inconsistent with other left panels. There are some other things we can do. Lets create a separate issue for this, because this has nothing to do with drag&drop inside the tree navigator.

**Comment by kof** [comment]
>  a collapse-all button

Also unrelated to drag&drop > separate issue

**Comment by kof** [comment]
> There's also the issue of naming elements.
> In Figma you can name layers directly (and most users don't). In Webflow the element name in the navigator is the name of the class.
> What do you think our approach should be here?

I think we should enable changing the name in-place in the navigator, since its a component name, not a class name + we should enable changing it in the style panel where we display the selected instance.

Also please create a separate issue.

**Comment by taylornowotny** [comment]
> > accordion-style opening/closing of parent elements to show/hide the children
> 
> Can you clarify more specifically what you think should happen?

This functionality is already in Webstudio so you can ignore that comment. I just have some ideas for how to improve the UX of this but I will express those visually in the design

**Comment by taylornowotny** [comment]
While some accordions may close other items when one is opened, it can also work the other way, where items stay open until they are closed deliberately. The latter is considered better UX in most cases because a user may want to see the content of multiple accordions at the same time.

**Comment by rpominov** [comment]
Webflow uses an interesting approach to render the tree. Instead of creating a tree out of DOM nodes, they put all nodes on the same level in the DOM creating a flat list, then add paddings to form a tree visually for the user.

Even if you change the order but not the nesting, they still don't move elements in the DOM, only use `transform()` to move them visually.

Not sure why they do that, but maybe to make DnD easier to implement. Probably not worth the refactor for us just yet, just something to keep in mind.

> enable dragging horizontally to change the parent but stay at the same level

This is the tricky one :)

> We should investigate if using react-dnd is the right idea for us in general, I didn't really like the way I had to set it up before, react-aria has an [interesting primitive](https://react-spectrum.adobe.com/react-aria/useMove.html), maybe its a better fit for us

Not sure we should do this on this low level of abstraction before we try to do it on a higher level. What about https://docs.dndkit.com/ ? It looks very well thought out and feature complete. 

For example, I like how they thought about different [collision detection algorithms](https://docs.dndkit.com/api-documentation/context-provider/collision-detection-algorithms) while with `useMove` whatever algorithm we need, we'll have to implement it ourself, and with react-dnd we get just one which may not work well for us.

There're many examples of what it can do: https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/core-draggable-hooks-usedraggable--basic-setup

I would try: dnd kit -> react-dnd -> useMove 
(moving to the next one if previous doesn't work for us)

**Comment by kof** [comment]
> Even if you change the order but not the nesting, they still don't move elements in the DOM, only use transform() to move them visually.

For sure easier with dnd, avoids the need to rerender the tree, so you can rerender just one node that was moved if its just indentation level, but then when rendering it would have to move anyways, so idk if its worth it

**Comment by kof** [comment]
> Not sure we should do this on this low level of abstraction before we try on a higher level. What about https://docs.dndkit.com/ ? It looks very well thought out and feature complete.

I haven't seen this one yet,  on a level of abstraction react-dnd looks nice too, right?

Well, I had so far 2 d&d usages of it and both have been quite non-standard, so almost none of the built-in logic was useful except for the basic draggable and getting coordinates:

1. Case 1: drag out of left sidebar onto canvas: canvas is an iframe, mouse events have to come from parent document and get mapped based on coordinates to the element on the canvas, then there is complex logic to determine where the element may drop. While dragging over canvas I had to put canvas on pointerEvents: none so that iframe doesn't steal the events. 
2. Case 2: dragging on the canvas: again same complex logic to determine the allowed drop target. In both cases, I am using 

On the other hand I don't know how much work it would be to rewrite all this to one approach and I bet react-dnd gives you enough primitive access to implement whatever is needed, so maybe we should stick with it to avoid having a zoo of libs, because that's bad for maintainability
