### ISSUE TITLE
Create a manual checklist for a PR template

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#169]
We need a checklist of all the things each PR author has to go throw and put a check mark before merging, things that are already in the CI don't need to be part of it, because already enforced:

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")
- [ ] expressed what kind of review is needed (conceptual, meticulous, with testing)
- [ ] if the PR is WIP, put it in draft mode

##  Test cases

- [ ] write step by step what interaction needs to be done and what is expected to happen

## Before merging

- [ ] Tested locally and on preview
- [ ] Updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document 
- [ ] Added a test if necessary
- [ ] If any new env variables are added to add them to the env.example and the env check if mandatory

**Comment by SaraVieira** [comment]
Made sure if there is a type with any there is a todo comment 

If any new env variables are added to add them to the env.example and the env check if mandatory

**Comment by kof** [comment]
any's are prevented by eslint

**Comment by SaraVieira** [comment]
It's only a warning i think

**Comment by kof** [comment]
please check, I was sure CI was not supposed to let you merge an any without an eslint-disable comment

**Comment by SaraVieira** [comment]
I had anys in the last PR because i had to pass the db

**Comment by SaraVieira** [comment]
perfect! Did you push it?

**Comment by kof** [comment]
Oh I just realized warnings are fine, we are not letting them pass on ci with max-warnings 0
