### ISSUE TITLE
Support Component Story Format (CSF)

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#24]
The idea is to use [csf](https://storybook.js.org/docs/react/api/csf) as a way to describe a component to the designer. 

This format should let a component express:

- controls in the properties and style panels
- supported values for style and properties
- enable designer render any component with a story out of the box

This is a complex topic that needs research and prototyping.

## Tasks

- [x] add stories to primitives and describe all available properties for each component (includes all available html properties)
- [x] make sure storybook can display those stories
- [x] render autocomplete inputs in props panel using options and controls from stories
- [x] think about how predefined styles on each component could also be expressed via CSF
- [x] support boolean prop types
- [x] support numeric prop types
- [x] use docgen to generate argTypes
- [x] improve types if needed for primitives to generate good argTypes
- [x] better ux that lets user discover properties

## PRs

- https://github.com/webstudio-is/webstudio-designer/pull/53
- https://github.com/webstudio-is/webstudio-sdk/pull/3

**Comment by SaraVieira** [comment]
- [ ] The HTML attribute `class` is not recognized as a valid attribute while classname is

**Comment by kof** [comment]
- [ ] cloned website in production now doesn't show correct attributes on elements: e.g. links don't have the href they used to have, saving new href works, but somehow we are not rendering the current value of an existing href neither in the properties panel nor on canvas

**Comment by kof** [comment]
I think we should close this one and create follow-up issues
