### ISSUE TITLE
Create a theme editor for design tokens

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#26]
We want to be able to create a theme for a project that allows to specify [theme](https://github.com/webstudio-is/webstudio-designer/blob/main/app/shared/design-system/stitches.config.ts#L132) that will be passed to [stitches](https://stitches.dev/docs/tokens)

We also need the default theme to be predefined and the ability to copy/paste a theme from one project to another project.

## Links

- figma tokens plugin https://docs.tokens.studio/

## Tasks

- [ ] decide where to have the editor and how it will look like
- [ ] load the default theme in the theme editor
- [ ] enable using the theme tokens from style panel

**Comment by kof** [comment]
closing in favor of a new issue
