### ISSUE TITLE
Migrate to an SQL Database

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#36]
## Use cases
- As a Webstudio hosted service, I need a scalable and cheap alternative to MongoDB.
- As an OSS contributor to Webstudio, I want an easy way to install the Designer and work with it locally
- As a Webstudio user I want run webstudio locally (offline in some future).

## Options

- SQLite for a local app
- supabase (PostgreSQL) for hosted service, deno workers in the same cluster would be also 🔥
- planetscale (MySQL)
- D1 cloudflare
- Others?

## Todo

- [ ] weigh in pros and cons of each database
- [ ] do we care if its MySQL vs PostgreSQL when using prisma?
- [ ] how hard is it to stay compatible with any of them, including SQLite?
- [ ] who offers the best scalable pricing?
- [ ] who offers hosting at the edge?
- [ ] who works with workers well? Problem with workers is they will create a lot of socket connections. Postgress has pgbouncer what is planetscale using for MySQL to scale it?

**Comment by SaraVieira** [comment]
I would at least for now go with Postgres for a couple of reasons

- Support in Prisma is slightly better 
- there's a lot of options to have these databases
- when using it with supabase we could also use their storage and auth and that would be a super huge deal to get into beta and allow people to upload fonts and images 
- i am not sure about workers but codesandbox used Postgres with live and we didn't have any issues whatsoever with it

**Comment by kof** [comment]
What just dropped https://blog.cloudflare.com/introducing-d1/ 🔥

**Comment by kof** [comment]
Given d1 is based on sqlite, maybe we should start with migrating to sqlite on any type of hosting for now and then start using d1 once available

**Comment by SaraVieira** [comment]
On it! Will start the migation across this repo and the SDK one

**Comment by SaraVieira** [comment]
Can you assign it to me?

**Comment by SaraVieira** [comment]
This is taking longer than expected for two reasons:

- No other database supports JSON as a tye in the database so I am at least for now stringifying everything
- Types in mongo had to be transformed to new models and so small calls like these:
```
await prisma.breakpoints.create({ data });
  ```

Have to be transformed into a massive call like so:

```
  const all = breakpoints.map(
    async (breakpoint: Breakpoint) =>
      await prisma.breakpoints.update({
        where: { treeId },
        data: {
          values: {
            create: breakpoint,
          },
        },
      })
  );
```

Since sqlite also does not support [createMany](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#remarks-9)

**Comment by kof** [comment]
Oh we should migrate to a schema, that JSON type was a workaround because prisma didn't support nested documents types

**Comment by SaraVieira** [comment]
ThG would be perfect in the future, for now we have will have to have a map 

Will love to know if we actually have the format of that JSON 

Will push both branches today so you can take a look

**Comment by kof** [comment]
that map looks like it won't be running those in parallel

**Comment by SaraVieira** [comment]
Oh, this is just a test before actually making a decent MR 

I was gonna use something like: https://www.npmjs.com/package/p-all that we use at remote

**Comment by SaraVieira** [comment]
This actually looks better 
https://github.com/sindresorhus/p-map

**Comment by kof** [comment]
Do we need to control the concurrency? I would have thought you want to run them in parallel always, so there is no need for an abstraction, its just javascript tm:

```js
  await Promise.all([
    prisma.breakpoints.update(...)
  ])
  ```
  
  Note how there is no await before ` prisma.breakpoints.update`
  
  But actually we should use [Prisma transaction](https://www.prisma.io/docs/concepts/components/prisma-client/transactions) I think it is the exactly right API for this, I don know why I even used Promise.all for this

**Comment by kof** [comment]
- [ ] Btw. lets also create a document for contributors on how to work with the db, basics with links to full docs.

**Comment by kof** [comment]
Found an interesting alternative to D1 https://dqlite.io/

**Comment by kof** [comment]
Another sqlite based alternative https://github.com/rqlite/rqlite

**Comment by kof** [comment]
Streaming replication for SQLIte https://litestream.io/

**Comment by SaraVieira** [comment]
Sounds perfect!

**Comment by kof** [comment]
Also should we migrate all the sites from mongo? If its too much work we should only migrate the landing. If that's too much work too, we can keep the landing the way it is in alpha and freeze it until beta
