### ISSUE TITLE
Assets manager

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#37]
As a user I need a way to upload a picture and use it as a background image or image component source.

## Tasks

- [ ] upload UI - Only allow images
- [ ] management UI
	- [ ] Remove assets
	- [ ] List assets by type
	- [ ] Add image to website
- [ ] file system upload for usage locally or in a docker
- [ ] upload to S3/R2 for hosted version

**Comment by SaraVieira** [comment]
Reference code: https://gist.github.com/SaraVieira/8cdb29104016ad5b9a164b19cf96e25e

Library: https://www.npmjs.com/package/multer-s3 & https://www.npmjs.com/package/multer

**Comment by SaraVieira** [comment]
Publishable parts:

- [ ] Upload single image locally(https://github.com/webstudio-is/webstudio-designer/pull/136)
- [ ] Add multi file support
- [ ] Fix image layouts with background fit and make them all same size
- [ ] Allow user to delete image
- [ ] Allow user to upload to s3

v1.1:

- [ ] Have nice uploading animation

**Comment by SaraVieira** [comment]
Things to think:

- Do we need the path in the DB?
