### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#39]
As a designer persona or as a developer persona I want to be able to log in to get access to my projects

## Tasks

- [ ] research a good way that is i locking us into some service and works well with workers-like environment e.g. https://github.com/sergiodxa/remix-auth

**Comment by SaraVieira** [comment]
Decisions so far:

- Stack: https://github.com/sergiodxa/remix-auth

Order:

- Google Signin: https://github.com/pbteja1998/remix-auth-google
- Github SignIn: https://github.com/sergiodxa/remix-auth-github

**Comment by SaraVieira** [comment]
Other related tasks:

- [ ]  Create database schema for users
- [ ]  Decide what data to get from users
- [ ] Create privacy policy

**Comment by kof** [comment]
At this point we will also need the GDPR thing, right?

**Comment by kof** [comment]
UI-wise 
- [ ] I would create a separate page that would show the login in the middle
- [ ] would automatically forward to /dashboard if user is already logged in
- [ ] /dashboard should automatically forward to /login if user is not logged in
- [ ] Optionally both /dashboard and /login could be the same route so we safe ourselves the redirects and just render conditionally from the same route?

**Comment by SaraVieira** [comment]
Routes should do this server-side correct?

> At this point we will also need the GDPR thing, right?

I don't think so because we don't have tracking and the only cookies we have are for login. If we do tracking I would say https://plausible.io/ is a good option as it's GDPR compliant.

We do need a privacy policy to say what we have in terms of the projects and user data from GitHub

**Comment by kof** [comment]
> Routes should do this server-side correct?

The idea behind Remix router is that it entirely automates this and makes it work with client-side navigation without full page reload if JS is enabled and works serverside if js is disabled or when user navigates directly to a specific page

**Comment by kof** [comment]
> I don't think so because we don't have tracking and the only cookies we have are for login. If we do tracking I would say https://plausible.io/ is a good option as it's GDPR compliant.

We are saving an auth token into the cookie and we can potentially ask user their name, email. So at this point we are tracking the user to even provide them login, right? I could be wrong

**Comment by SaraVieira** [comment]
I am also not sure but I think login cookies do not count for GDPR

**Comment by kof** [comment]
Apparently we don't need the cookie banner as long as we keep the analytics/auth info in our servers, not share it with 3rd party https://github.blog/2020-12-17-no-cookie-for-you/

This is nice!

**Comment by SaraVieira** [comment]
Tasks:

- [ ] Login with github
- [ ] Dev login
- [ ] Google login
- [ ] Create docs for contributors
- [ ] Create testing docs
- [ ] Show errors when something goes wrong
