### ISSUE TITLE
New spacing UI

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#421]
Current UI was made without proper design and we now have CSS value input we want to use in it.

New design is still in tweaking, but it will looks something like this:
<img width="227" alt="Screenshot 2022-11-08 at 10 10 17" src="https://user-images.githubusercontent.com/52824/200522955-cf52fb1a-3b3c-42dd-a48f-29c2c448ae30.png">

https://www.figma.com/file/EfzZ2w94KpmUviZJSBgxCd/Designer-UI?node-id=1142%3A20479

## Todo

- [x] use svg from figma to render the 3d-shaped control.
- [x] hover and click of controls has the non-rect form, so we need to render svg as component and work with it's paths/shapes for event handling
- [x] use scrub primitives we already have to add scrub to the controls
- [x] each control should have a cursor showing the right direction (see wf)
- [x] click on the control should open the CSS value input as demonstrated [here](https://github.com/webstudio-is/webstudio-designer/pull/401 )
- [x] CSS value input also has scrub built in and should also work when opened
- [x] Rendering the value in control 
   - [x] when value is too long, we need to start rendering unit on the next line.
   - [ ] when value is in px, we don't show the px in the control
   - [ ] when value is still too long after unit is on the next line, we should center the value so that it grows like wf does this.
   
   
 Here is a prototype of the  value input based on the current spacing UI [see PR](https://github.com/webstudio-is/webstudio-designer/pull/401 )
     

https://user-images.githubusercontent.com/52824/200816742-108bed81-54f3-4a31-9e2d-e68e59b9f09f.mp4

---------------

https://www.figma.com/file/EfzZ2w94KpmUviZJSBgxCd/Designer-UI?node-id=3024%3A44415&t=pMvbZ6AkTH7iyihi-4
![image](https://user-images.githubusercontent.com/825702/204998404-4c60e0f8-2023-44d4-a8bf-e4d4e54a6841.png)

**Comment by kof** [comment]
Regarding keyboard accessibility: I think we should
- [ ] focus/outline the entire control on tab
- [ ] then once focus-within, use arrow keys to select the specific item (circular key logic)
- [ ] enter should be the same as click
- [ ] esc would close popover with CSS value input and return focus to the last item, so one can hit enter again

**Comment by kof** [comment]
We have the problem with focus state of internal components of a component in 2 other places as well and it looks like a pattern, I think we should decide what we do there now, before it creates more technical debt.

From keyboard navigation it makes sense to navigate components with a tab and navigate internal things with arrows as opposed to making everything navigatable with a tab.

Tab is great until you have too many things, then tab becomes unusable because you have to tab through too many things.

**Comment by kof** [comment]
My proposal is:

1. use tab to select the spacing UI, another tab will focus next control outside of spacing UI
2. use arrows to focus any internal control
3. keep the spacing UI is always focused no matter which control inside it is being currently focused (:focus-within on the spacing)


Same goes for lists with buttons inside the list items:

1. Tab between the list items, don't tab inside the list item
2. Inside the list item support arrow keys

**Comment by taylornowotny** [comment]
I have no objections to @kof 's suggestion. I agree that it's a good idea to use arrows to focus within or else it could take too many tabs to focus the intended thing.

I will design a focus state for the whole input. Using the hover style for internal focus here is fine. 

BTW webflow's spacing section is completely inaccessible. Can't focus any part of it.

**Comment by taylornowotny** [comment]
<img width="409" alt="Screenshot 2022-12-15 at 11 34 12 AM" src="https://user-images.githubusercontent.com/86495896/207952388-389b2c0b-320b-442f-8d62-f77fdf3b42a2.png">

Does this work for you @rpominov ?

Can a user easily focus within to change padding? Or do we need a focus for margin and padding separately?

**Comment by rpominov** [comment]
Looks good.

> Can a user easily focus within to change padding? Or do we need a focus for margin and padding separately?

Yes. I think it's going to work like this:

As you focus the entire control with tab, the `margin-top` inside also becomes focused. Then you can move focus inside with arrows like this:

<img width="688" alt="Screenshot 2022-12-16 at 11 25 33" src="https://user-images.githubusercontent.com/825702/208045514-732502e9-7080-4cbd-9d82-4a282b36768b.png">
