### ISSUE TITLE
Tokens Manager

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#494]
Based on this user story https://github.com/webstudio-is/webstudio-designer/issues/422

As a user, I need a way to define and apply atomic tokens to the style panel.

## Concept

The user opens a tokens picker panel that is positioned next to the style panel.
When the tokens picker is open you fundamentally need to have selected the "destination" and the "source".  
The destination is any style value (can be a property name, value button-menu, select, CSS Value Input, or anything else we use). The source is the token item from the tokens picker.

You can select a destination first, and a source second. You can select source first, and destination second. You can drag the source onto the destination (probably for later).

Once both are selected, a token value (the actual value, e.g. #000 color) applies to the style panel and canvas. The label or the button for that label receives token color coding (green?). The actual value in the data is not just a value, it's a CSS variable.
From now on, this variable can be changed in the tokens manager and reflect automatically on all consumers.

## Todo
- [ ] Decide what button will open the tokens picker
- [ ] `ctrl+t` will open the same tokens picker
- [ ] Open floating window
- [ ] How do we position that window?
- [ ] Tokens picker renders collapsible sections like style panels and lists of tokens inside of each panel
- [x] Each panel header has a + button to add a new token
- [x] Each section represents a token group. Groups can be predefined.
- [x] Each token will have a menu button (like fonts picker) and menu will have delete and edit items
- [x] Edit item opens n inline dialog with: name input, CSS value input, description textarea, cross-icon button
- [x] Changes in the tokens editor live-preview just like style panel changes and save on enter/blur
- [x] ~Data structure we save tokens in is defined by the [spec](https://design-tokens.github.io/community-group/format/) ~ - it's bad, we will support the official format for importing/exporting but won't use it internally
- [ ] fetch and render tokens on the edge
- [ ] Need to figure out if/how to copy tokens/bindings that are used on a component that we copy/pasted
- [ ] Do we want to enable copying any value from style panel so it can be pasted into token editor?

**Comment by taylornowotny** [comment]
CMD + T in a browser window opens a new tab. Seems like a common shortcut that we might not want to overwrite. Any other shortcut ideas?

**Comment by kof** [comment]
Simply `t` without cmd? or option+t or ctrl+t 

Need to also check if those are not used in some popular way by figma and webflow.

**Comment by taylornowotny** [comment]
> Simply `t` without cmd? or option+t or ctrl+t
> 
> Need to also check if those are not used in some popular way by figma and webflow.

T by itself does nothing in Webflow, in Figma it opens the text tool.
OPTION + T does nothing that I can tell in either program.

both would be good shortcuts AFAIK

**Comment by kof** [comment]
CTRL+T also does nothing and ctrl is better since its used cross-platform, for all other shortcuts we always have to use a different modifier key on windows, eg.g. cmd+s on mac, ctrl+s on windows, so for tokens we should go straight with ctrl+t

**Comment by kof** [comment]
@taylornowotny what idea do you have for placing the button that opens token picker?

**Comment by taylornowotny** [comment]
> @taylornowotny what idea do you have for placing the button that opens token picker?

Sorry just saw this. I would say proximal to the style panel if the window is going to open next to the style panel. Above or below the selector field, or as a button on the right side of the top bar. I'll figure this out for sure when I have time to focus on designing this UI

**Comment by kof** [comment]
@taylornowotny something to think about: tokens have those predefined groups when the entire panel is open it looks like this on the screen. This is fine when its about managing all the tokens, but when you are trying to pick the token, we probably need a way to reduce the list, because that would be quite hard to find the right token potentially every time you need one.

I was thinking maybe when showing token picker on the right, we could either have a tokens button in each section separately and this way we know what token group(s) to show or something like this ...


<img width="316" alt="Screenshot 2022-11-25 at 20 25 14" src="https://user-images.githubusercontent.com/52824/204044767-648a1498-a805-47de-9503-c77f068fe823.png">

**Comment by taylornowotny** [comment]
Good ideas. I’ll save this for consideration when I design the UX & UI

**Comment by kof** [comment]
Another idea would be some kind of groups list similar to navigator and once selected tokens in the content, so that a lot of groups don't take that much space and we can also use the tokens picker in each section in style panel to jump directly to a specific group

**Comment by kof** [comment]
will open a new issue once we resume work on tokens manager
