### ISSUE TITLE
Multi-page sites and routing

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#54]
As a user I want to be able to create multiple pages and leverage the full power of Remix's router, which doesn't need to do the full page reload between pages once loaded and makes it super fast

## Todo

- [x] Create prisma model (discussed: {id, projected, data: JSON})
- [x] Create a migration for the production database (using [snaplet](https://twitter.com/appfactory/status/1559505547526897667)?)
- [x] Create rest API
- [x] Create data zod schema
- [x] Create  db helpers
- [x] Render the panel in the left sidebar
- [ ] Render the pages tree using tree component we use in navigator
- [x] Page item has 2 main functions: open the page and open the page settings
- [ ] Page item can have a parent
- [ ] Page settings should have a few main key/values predefined, the rest should be added by the user with "+"  and selected from predefined known list + any key/value user wants that will be rendered `<meta content="" property=""/>`
- [ ] Write a Page component for SDK that will render title/meta and replace the current `shared/documents/Canvas.tsx`
- [x] Add new page
- [ ] Set a page as a home page (only one page can be home and should have path as empty, that's how we can indicate in the db the home page)
- [ ] Apply final design 

![Pages Panel](https://user-images.githubusercontent.com/825702/193991016-f05b4bf5-f798-498a-ac41-5640fbabcdac.jpg)

**Comment by kof** [comment]
Currently known questions:

1. Do we want a folder or do we want pages to be nestable?
2. Should folder add a prefix to the path? always? optionally? which one would be by default?

Things to consider:
- if we use folder to auto-add a path prefix, we enforce a more rigid structure for URLs for everything that goes in the folder, so this makes it easy to have a consistent URLs structure like /blog/some-post for all the posts but at the same time if folder is not something meaningful you want to have in the URL, it will just add to the URL useless stuff
- if we have pages instead of folders it would allow have an overview page that links to details like for. /blog it would list a list of posts and /blog/some-post would be the actual post
- in both cases we could make path on folder/page optional and simply disable it or let it be removable, in this case a page without a path is just a folder

**Comment by rpominov** [comment]
I've created a bunch of separate issues for everything remaining to do: https://github.com/webstudio-is/webstudio-designer/labels/area%3Apages

Will close this one
