### ISSUE TITLE
Restrict dropping instances into certain instance types

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-designer#7]
Some instances can't accept children at all (Input), some only accept specific components, e.g. div can't be inside paragraph

## Todo
- [x] prevent inserting into components which don't accept an instance
- [x] outline during drag the instance that will accept the insteance instead of the one that can't
- [x] when single-click adding an instance while the target instance can't accept it automatically select the closest parent instance that can ([duplicate issue ](https://github.com/webstudio-is/webstudio-designer/issues/109))

**Comment by kof** [comment]
Todo: check if we can create a function that inserts an element into the target element before it gets inserted to validate if there is a thrown "validateDOMNesting" before it actually happens and then prevents inserting and then show an error to the user also  make the target show it doesn't accept the node

**Comment by kof** [comment]
This is where this warning is coming from, its not DOM, its react https://github.com/facebook/react/blob/main/packages/react-dom/src/client/validateDOMNesting.js

we should probably just copy that and use as pre-validation, but also this is only logging in dev mode and not affecting any production

**Comment by kof** [comment]
Deprioritizing this issue for now

**Comment by kof** [comment]
Actually found this library that can be introduced easily https://github.com/MananTank/validate-html-nesting

**Comment by kof** [comment]
We should at least disable for now basic things: e.g. h1 should get into Text/Paragraph etc. and respect the .canAcceptChild function on primitives

**Comment by rpominov** [comment]
Can we close this now, or do we still want to use something like [validate-html-nesting](https://github.com/MananTank/validate-html-nesting)?

**Comment by kof** [comment]
I would say lets close, we will potentially have to come back to it at some point once we see more concrete use cases.
Originally I thought of a generic validator that is based on HTML spec is a good idea because it would work for any components, but then I realized that you don't want certain components be dropped into certain components: e.g. div into h1, even though it would technically still work, so a generic HTML based linter is not quite solving the problem. We need to think more about this problem to enable something that would work for all components and for custom sdk's.

Maybe we can come up with a higher level API that would have HTML constraints backed in and on top of that allow caller to specify additional constraints ... adk

**Comment by kof** [comment]
Actually, I just recall the original reason is that React has its own built-in validator and warns in dev mode when nodes are nested illegally. It's a much smaller subset of HTML it seems and I don't know how correct it actually is.
