### ISSUE TITLE
DB Performance and login issues

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-designer#812]
Now we have error "Transaction already closed could not perform operation"
That is caused that transactions are closed by timeout which is 5s default in Prisma https://www.prisma.io/docs/concepts/components/prisma-client/transactions

Mostly its because we do updates in cycle inside transactions here https://github.com/webstudio-is/webstudio-designer/blob/fd99c4f542272856dd205c7be81d7dcc7a694840/packages/project/src/db/props.ts#L141

Additionally, we have similar logic at `patch` in the same file.

The other problem is that rollbacked transactions didn't prevent us to create a broken Project i.e. project without "dev" build.

Now we have 23 
```sql
select "Project".id from "Project" left join "Build" ON "Project".id = "Build"."projectId" AND "Build"."isDev"=TRUE 
WHERE "Build".id is NULL
```

What to do:

### ASAP
- [x] - fix the performance of clone operations or increase the transaction timeout. ref #811 uses `createMany`
- [x] - fix the transaction - project must not be created if clone fails ref #811
- [x] - add an index to speedup patch and clone  ref #811
- [x] - using SQL above drop all broken projects from production SQL

#### OR DO THIS
- [ ] - patch must not read all properties from the DB (only changed)
- [ ] - patch must not update all properties in DB (only patched)

#### OR THIS
- [x] - move instance props into the tree field as @TrySound suggested.

**Comment by TrySound** [comment]
Props are moved to tree table
